# Generated by Django 5.1.7 on 2025-05-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
